// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-IAFzyL_tbLMn1FuHx_9j2sF2PbTYjz8',
    appId: '1:178768912502:web:6b6db486aff9cccc92bf57',
    messagingSenderId: '178768912502',
    projectId: 'newproject-d0032',
    authDomain: 'newproject-d0032.firebaseapp.com',
    storageBucket: 'newproject-d0032.appspot.com',
    measurementId: 'G-4RR9DXZE7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKeTovqEnFLZIBFGrnJ5-U0oCSlsxSm50',
    appId: '1:178768912502:android:d3020528594b101c92bf57',
    messagingSenderId: '178768912502',
    projectId: 'newproject-d0032',
    storageBucket: 'newproject-d0032.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqaB1gHvL1OwSI9SJy4Bls2RgLV_owyb0',
    appId: '1:178768912502:ios:72eca1acca8cb53f92bf57',
    messagingSenderId: '178768912502',
    projectId: 'newproject-d0032',
    storageBucket: 'newproject-d0032.appspot.com',
    androidClientId: '178768912502-5r39q4eam3ueuimlc6dsna1fapcgsj72.apps.googleusercontent.com',
    iosClientId: '178768912502-cr0a3mbd23ack0187bdddu59q849jl01.apps.googleusercontent.com',
    iosBundleId: 'com.example.newproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqaB1gHvL1OwSI9SJy4Bls2RgLV_owyb0',
    appId: '1:178768912502:ios:72eca1acca8cb53f92bf57',
    messagingSenderId: '178768912502',
    projectId: 'newproject-d0032',
    storageBucket: 'newproject-d0032.appspot.com',
    androidClientId: '178768912502-5r39q4eam3ueuimlc6dsna1fapcgsj72.apps.googleusercontent.com',
    iosClientId: '178768912502-cr0a3mbd23ack0187bdddu59q849jl01.apps.googleusercontent.com',
    iosBundleId: 'com.example.newproject',
  );
}
